---
--- KEYS[1]:lock_key
--- ARGV[1]:expire_mills
--- ARGV[2]:thread_id
--- Generated by Luanalysis
--- Created by ctl.
--- DateTime: 2022/7/6 15:37
---
if (redis.call('hexists', KEYS[1], ARGV[2]) == 0) then
    return nil;
end ;
local counter = redis.call('hincrby', KEYS[1], ARGV[2], -1);
if (counter > 0) then
    redis.call('pexpire', KEYS[1], ARGV[1]);
    return 0;
else
    redis.call('del', KEYS[1]);
    return 1;
end ;
return nil;

