---
--- redis2.6.12版本后set命令支持ex(px)和nx；
--- 下面lua脚本相当于命令：SET lock_key thread_id NX PX 30000
---
--- Generated by Luanalysis
--- Created by ctl.
--- DateTime: 2022/7/6 10:02
---
if (redis.call('setnx', KEYS[1], ARGV[1]) == 1) then -- 不存在才设值
    redis.call('expire', KEYS[1], ARGV[2]) -- 设值成功再指定过期时间
    return true
else
    return false -- 设值失败
end