---
--- Generated by Luanalysis
--- Created by ctl.
--- DateTime: 2022/7/6 13:49
---
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    -- value为自身线程加锁时的值才允许删除，防止误解锁
    redis.call('del',KEYS[1])
    return true
else
    return false
end
